name: shop_6
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.6
  flutter_svg: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - assets/images/create_account_bubbles.png
    - assets/images/login_bubbles.png
    - assets/images/password_bubbles.png
    - assets/images/flag.png
    - assets/images/icon.png
    - assets/images/product1.png
    - assets/images/product2.png
    - assets/images/product3.png
    - assets/images/product4.png
    - assets/images/product5.png
    - assets/images/product6.png
    - assets/icons/home.svg
    - assets/icons/favorite.svg
    - assets/icons/cart.svg
    - assets/icons/delete.svg
    - assets/icons/less.svg
    - assets/icons/more.svg
    - assets/icons/eye-slash.svg

  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Regular.ttf
        - asset: assets/fonts/Raleway-Medium.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Raleway-Bold.ttf
          weight: 700
        - asset: assets/fonts/Raleway-ExtraBold.ttf
          weight: 800

    - family: NunitoSans
      fonts:
        - asset: assets/fonts/NunitoSans-VariableFont_YTLC,opsz,wdth,wght.ttf


flutter_native_splash:
  color: "#F2F2F2"  
  image: "assets/images/icon.png"
  android_12:
    image: "assets/images/icon.png"
    icon_background_color: "#FFFFFF"

  ios: true
  web: true
  fullscreen: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/images/icon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/images/icon.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/images/icon.png"